IF (SELECT count(*) FROM ENIQ_EVENTS_ADMIN_PROPERTIES WHERE PARAM_NAME='ENIQ_EVENTS_LOCK_USERS') = 0
BEGIN
	INSERT INTO ENIQ_EVENTS_ADMIN_PROPERTIES (PARAM_NAME, PARAM_VALUE, MODIFIED_BY) VALUES ('ENIQ_EVENTS_LOCK_USERS', 'false', 'dcuser')
END

IF (SELECT count(*) FROM ENIQ_EVENTS_ADMIN_PROPERTIES WHERE PARAM_NAME='ENIQ_EVENTS_MAX_USER_SESSIONS') = 0
BEGIN
	INSERT INTO ENIQ_EVENTS_ADMIN_PROPERTIES (PARAM_NAME, PARAM_VALUE, MODIFIED_BY) VALUES ('ENIQ_EVENTS_MAX_USER_SESSIONS', '150', 'dcuser')
END

IF (SELECT count(*) FROM ENIQ_EVENTS_ADMIN_PROPERTIES WHERE PARAM_NAME='ENIQ_EVENTS_BANNER_MESSAGE') = 0
BEGIN
	INSERT INTO ENIQ_EVENTS_ADMIN_PROPERTIES (PARAM_NAME, PARAM_VALUE, MODIFIED_BY) VALUES ('ENIQ_EVENTS_BANNER_MESSAGE', '', 'dcuser')
END

